In [1]:
import tensorflow as tf
import numpy as np

In [11]:
x_data = [[1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7]]
y_data = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]]

X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 3])

W = tf.Variable(tf.random_normal([4, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) +  b) 

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis),axis=1))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1)
optimizer = train.minimize(cost)


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, {X:x_data, Y:y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, {X:x_data, Y:y_data}))
    
    a = sess.run(hypothesis, {X:[[1,11,7,9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(a, sess.run(tf.argmax(a, 1)))
            
            

0 2.7825418
200 0.6987525
400 0.5900732
600 0.49739775
800 0.40812528
1000 0.31907701
1200 0.24302517
1400 0.21917456
1600 0.20028608
1800 0.1842498
2000 0.17048165
[[4.2800743e-02 9.5718998e-01 9.2279215e-06]
 [6.5054584e-01 3.2323220e-01 2.6221922e-02]
 [2.5076037e-08 4.2230453e-04 9.9957770e-01]] [1 0 2]


In [35]:
xy = np.loadtxt("data-04-zoo.csv", delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])
nb_classes = 7
Y_one_hot = tf.one_hot(Y, nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])

W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits, labels=Y_one_hot)
cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis,1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot,1)) 
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32)) 

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2000):
        sess.run(optimizer, {X:x_data, Y:y_data})
        loss, acc = sess.run([cost, accuracy], {X:x_data, Y:y_data})
        if step%100 == 0:
            print(step, loss, acc)
    
    pred = sess.run(prediction, {X:x_data})
    for p,y in zip(pred, y_data.flatten()):
        print(p==y, p, y)



0 3.101439 0.4059406
100 0.73867965 0.76237625
200 0.4808442 0.8118812
300 0.3503419 0.8811881
400 0.27217177 0.8910891
500 0.22079375 0.9405941
600 0.18485636 0.96039605
700 0.15851718 0.980198
800 0.13849664 0.990099
900 0.12282852 0.990099
1000 0.11026867 1.0
1100 0.09999597 1.0
1200 0.09144987 1.0
1300 0.08423642 1.0
1400 0.07807139 1.0
1500 0.07274538 1.0
1600 0.068100475 1.0
1700 0.064015746 1.0
1800 0.060396966 1.0
1900 0.057169665 1.0
True 0 0.0
True 0 0.0
True 3 3.0
True 0 0.0
True 0 0.0
True 0 0.0
True 0 0.0
True 3 3.0
True 3 3.0
True 0 0.0
True 0 0.0
True 1 1.0
True 3 3.0
True 6 6.0
True 6 6.0
True 6 6.0
True 1 1.0
True 0 0.0
True 3 3.0
True 0 0.0
True 1 1.0
True 1 1.0
True 0 0.0
True 1 1.0
True 5 5.0
True 4 4.0
True 4 4.0
True 0 0.0
True 0 0.0
True 0 0.0
True 5 5.0
True 0 0.0
True 0 0.0
True 1 1.0
True 3 3.0
True 0 0.0
True 0 0.0
True 1 1.0
True 3 3.0
True 5 5.0
True 5 5.0
True 1 1.0
True 5 5.0
True 1 1.0
True 0 0.0
True 0 0.0
True 6 6.0
True 0 0.0
True 0 0.0
True 0 0.0
Tru